baseURL = "https://haiderijlal.github.io/"
languageCode = "en-us"
title = "Syed Ijlal Haider"
theme = "simply"

paginate = 10

[params]
  mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
  subtitle = "The whole is greater than the sum of its parts — Aristotle"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/haiderijlal"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/syed-ijlal-haider-8371185a/"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:ijlal.haider26@gmail.com"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4


